-- Add RUNBOOK_DUE to notifications.type (MySQL/TiDB enum).
ALTER TABLE `notifications`
  MODIFY COLUMN `type` ENUM('IDLE_FLAG', 'MITOSIS_ALERT', 'MERGER_SUGGESTION', 'MENTION', 'ROLE_ASSIGNED', 'RUNBOOK_DUE') NOT NULL;
